apiVersion: apps/v1
kind: Deployment
metadata: 
  name: miketest
  namespace: default
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mike
  template:
    metadata:
      labels:
        app: mike    
    spec:
      containers:
      - name: mike-test
        image: mgarfias/mike-test
        livenessProbe:
          exec:
            command: 
            - /bin/sh
            - -c 
            - "curl http://localhost:8000/bytes/21"

---
apiVersion: v1
kind: Service
metadata:
  name: mike-test
  namespace: default
spec:
  type: NodePort
  selector:
    app: mike
  ports:
   - port: 8000
     targetPort: 8000
     nodePort: 32000
